version: '3.8'

services:
  api:
    depends_on:
      - toko
    build:
      context: .
    container_name: rest-server
    hostname: rest-server
    networks:
      - tokonet
    ports:
      - 80:80
      - 8081:8081
    deploy:
      restart_policy:
        condition: on-failure
  toko:
    image: mysql
    container_name: toko
    hostname : db
    networks: 
      - tokonet
    ports:
      - 3306:3306
      - 8080:8080
     environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
     vokumes:
      - toko:/var/lib/mysql
      
 volumes:
  toko:
 networks:
  tokonext:
    driver: bridget

